#import "@preview/charged-ieee:0.1.4": ieee

#show: ieee.with(
    title: [Assignment 3],
    authors: (
        (
            name: "Luis Dale Gascon",
            department: [Computer Science],
            organization: [Towson University],
            email: "lgascon1@students.towson.edu",
        ),
    ),
    index-terms: ("coffee", "clustering"),
    bibliography: bibliography("refs.bib"),
    figure-supplement: [Fig.],
    abstract: [
      This paper investigates the relationship between the geographic origin of coffee and its sensory characteristics by applying unsupervised clustering methods to a dataset of coffee evaluations. The dataset includes features such as aroma, flavor, aftertaste, acidity, and balance, along with the country of origin for each sample. We compare the effectiveness of three clustering algorithms HDBSCAN, Agglomerative Clustering, and Mean Shift in grouping coffees based on their sensory profiles. Our analysis aims to determine whether coffees from the same region exhibit similar taste profiles and to what extent geography influences sensory perception. The results provide insights into the role of origin in shaping coffee quality and inform both producers and consumers about the potential of clustering techniques in coffee analysis.
    ]
)

= Introduction



= Problem

We want to investigate whether there's an aromatic pattern to coffee beans based on the geographical region that it was harvested from. 

= Dataset

The dataset contains 41 columns, 14 of which we decided to drop. The columns that we decided to drop are 
- `Unnamed: 0` 
- `ID`
- `Defects` 
- `Status`
- `Farm Name` 
- `Lot Number` 
- `Mill` 
- `ICO Number` 
- `Company`
- `Producer`
- `Status`
- `Certification {Body, Address, Contact}`

The columns listed above just add noise.
The dataset is fairly small at 207 rows in total. 

= Data Analysis

Focusing on the features relating to geography, we wanted to analyze the 

= Background

Before we implement the clustering algorithms listed above, we need to provide some background information about each algorithm.

== DBSCAN

A density-based clustering method 

== Mean-Shift

Similar to DBSCAN, it doesn't assume a predefined shape for clusters, which allows it to handle clusters of arbitrary shapes

== Agglomerative Clustering

A bottom-up approach to hierarchical clustering.

= Methodology

We want to explore 3 different clustering algorithms for our analysis. We will be comparing DBSCAN, Agglomerative and Mean Shift clustering algorithms. 

For our evaluation metric we will be taking the Silhoutte score of the clusters generated by each clustering algorithms


= Results

= Evaluating the Results
